### ISSUE TITLE
No RBAC support

### ISSUE THREAD

**Issue by shanoor** [ollystephens/acme-kong-kube-helper#1]
First, thank you for this helper. Like many, I have issues with Kong and Cert-manager working together so I tried your helper and realised there is no support for RBAC-enabled cluster:

    E0321 10:09:23.210174       1 reflector.go:134] app/main.go:87: Failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:default:default" cannot list resource "ingresses" in API group "extensions" at the cluster scope

**Comment by ollystephens** [comment]
Hi Shanoor. Make sure you are running the container with the same privileges as the kong-ingress-controller. It needs to be able to watch the whole cluster for ingress events too. The easiest way to do this is to include the container in the same pod as the ingress controller. That's what I do and it is working for me (I'm in an RBAC-enabled cluster too). If you don't want to do that, then second easiest way is to make sure it's running with the same serviceaccount.

**Comment by shanoor** [comment]
Thanks, I'm using Helm for Kong, so I specified a serviceAccount for the helper's deployment, it's working.

Now I have an another issue, the pod is constantly crashing: 

	panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xff8b1c]

	goroutine 37 [running]:
	main.patchKong(0xc0000df7c0, 0x47)
			/go/src/app/main.go:134 +0xabc
	created by main.main.func1
			/go/src/app/main.go:81 +0x312

**Comment by ollystephens** [comment]
OK, yep, that's a bug. Standby for a 0.0.2 build...

But I can tell you that it's failing to talk to kong. My guess is that it's not finding the admin endpoint. Make sure your `-kong-url` is correctly set. If you are deploying a separate pod, the default won't work; you'll probably need to set it to something like `http://kong-ingress-controller:8001` (depending on what your other pod is called).

**Comment by shanoor** [comment]
You're right, the endpoint was not good and I had to disable TLS on the Kong Admin pod to make it work.

**Comment by ollystephens** [comment]
Yeah, it doesn't support TLS on the admin endpoint.
